### ISSUE TITLE
single HTTP request logged twice in the development

### ISSUE THREAD

**Issue by Sohair63** [tongueroo/jets#195] opened 2019-02-15 11:45 UTC
A single HTTP request logged twice in the development as shown below.

- simply click on any link
- check the logs you will see two logs with different timestamps

```
I, [2019-02-15T16:39:56.017972 #72689]  INFO -- : Started GET "/posts/1" for 127.0.0.1 at 2019-02-15 16:39:56 +0500
I, [2019-02-15T16:39:56.018098 #72689]  INFO -- : Processing PostsController#show
I, [2019-02-15T16:39:56.018272 #72689]  INFO -- :   Event: {"resource":"/posts/{id}","path":"/posts/1","httpMethod":"GET","headers":{"Host":"127.0.0.1:8888","Connection":"keep-alive","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9,fr;q=0.8","Cookie":"PGADMIN_LANGUAGE=en; PGADMIN_KEY=3dc5f098-474e-4d05-9a75-18b5f6c477f5; _ga=GA1.1.25457488.1550058379; _gid=GA1.1.65919826.1550230412","Version":"HTTP/1.1","cache-control":"max-age=0","upgrade-insecure-requests":"1"},"queryStringParameters":{},"pathParameters":{"id":"1"},"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
I, [2019-02-15T16:39:56.018396 #72689]  INFO -- :   Parameters: {"id":"1"}
I, [2019-02-15T16:39:56.091956 #72689]  INFO -- : Completed Status Code 200 in 0.074126s
127.0.0.1 - - [15/Feb/2019:16:39:56 +0500] "GET /posts/1 HTTP/1.1" 200 - 0.1018
I, [2019-02-15T16:40:00.091567 #72690]  INFO -- : Started GET "/posts/1" for 127.0.0.1 at 2019-02-15 16:40:00 +0500


I, [2019-02-15T16:40:00.091681 #72690]  INFO -- : Processing PostsController#show
I, [2019-02-15T16:40:00.091868 #72690]  INFO -- :   Event: {"resource":"/posts/{id}","path":"/posts/1","httpMethod":"GET","headers":{"Host":"127.0.0.1:8888","Connection":"keep-alive","Pragma":"no-cache","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9,fr;q=0.8","Cookie":"PGADMIN_LANGUAGE=en; PGADMIN_KEY=3dc5f098-474e-4d05-9a75-18b5f6c477f5; _ga=GA1.1.25457488.1550058379; _gid=GA1.1.65919826.1550230412","Version":"HTTP/1.1","cache-control":"no-cache","upgrade-insecure-requests":"1"},"queryStringParameters":{},"pathParameters":{"id":"1"},"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
I, [2019-02-15T16:40:00.092015 #72690]  INFO -- :   Parameters: {"id":"1"}
I, [2019-02-15T16:40:00.144972 #72690]  INFO -- : Completed Status Code 200 in 0.053526s
127.0.0.1 - - [15/Feb/2019:16:40:00 +0500] "GET /posts/1 HTTP/1.1" 200 - 0.0745
```

**Comment by tongueroo** [comment] 2019-02-15 20:14
🤔 Unable to reproduce. Hit it via curl as well as in Chrome. Thinking that there's probably some extension that might be causing that 2nd request?  Would try with via curl on your machine to see if it's a specific browser issue. Then would try different browser or Chrome incognito.

    I, [2019-02-15T20:10:37.105468 #8014]  INFO -- : Started GET "/" for 127.0.0.1 at 2019-02-15 20:10:37 +0000
    I, [2019-02-15T20:10:37.105523 #8014]  INFO -- : Processing Jets::PublicController#show
    I, [2019-02-15T20:10:37.105795 #8014]  INFO -- :   Event: {"resource":"/","path":"/","httpMethod":"GET","headers":{"Host":"localhost:8888","User-Agent":"curl/7.53.1","Accept":"*/*","Version":"HTTP/1.1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:10:37.105843 #8014]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:10:37.131045 #8014]  INFO -- : Completed Status Code 200 in 0.025609602s
    127.0.0.1 - - [15/Feb/2019:20:10:37 +0000] "GET / HTTP/1.1" 200 - 0.0602
    
    I, [2019-02-15T20:10:57.173122 #8050]  INFO -- : Started GET "/posts" for 127.0.0.1 at 2019-02-15 20:10:57 +0000
    I, [2019-02-15T20:10:57.173180 #8050]  INFO -- : Processing PostsController#index
    I, [2019-02-15T20:10:57.173243 #8050]  INFO -- :   Event: {"resource":"/posts","path":"/posts","httpMethod":"GET","headers":{"Host":"localhost:8888","User-Agent":"curl/7.53.1","Accept":"*/*","Version":"HTTP/1.1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:10:57.173289 #8050]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:10:57.228170 #8050]  INFO -- : Completed Status Code 200 in 0.055083429s
    127.0.0.1 - - [15/Feb/2019:20:10:57 +0000] "GET /posts HTTP/1.1" 200 - 0.0712
    
    I, [2019-02-15T20:11:11.534508 #8107]  INFO -- : Started GET "/posts" for 11.123.123.123 at 2019-02-15 20:11:11 +0000
    I, [2019-02-15T20:11:11.534564 #8107]  INFO -- : Processing PostsController#index
    I, [2019-02-15T20:11:11.534648 #8107]  INFO -- :   Event: {"resource":"/posts","path":"/posts","httpMethod":"GET","headers":{"Host":"cloud9.tung.boltops.com:8888","Connection":"keep-alive","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Accept-Encoding":"gzip, deflate","Accept-Language":"en-US,en;q=0.9,pt;q=0.8","Version":"HTTP/1.1","upgrade-insecure-requests":"1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:11:11.534694 #8107]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:11:11.570395 #8107]  INFO -- : Completed Status Code 200 in 0.035924576s
    11.123.123.123 - - [15/Feb/2019:20:11:11 +0000] "GET /posts HTTP/1.1" 200 - 0.0510

Closing out to not meeting the issues requirements. 👌

**Closed by tongueroo** 2019-02-15 20:14 UTC
Labels: bug

**Comment by tongueroo** [comment] 2019-02-15 20:16
🤔 Unable to reproduce. Hit it via curl as well as in Chrome. Thinking that there's probably some extension that might be causing the 2nd request?  Would try with via curl on your machine to see if it's a specific browser issue. Then would try different browser or Chrome incognito.

    I, [2019-02-15T20:10:37.105468 #8014]  INFO -- : Started GET "/" for 127.0.0.1 at 2019-02-15 20:10:37 +0000
    I, [2019-02-15T20:10:37.105523 #8014]  INFO -- : Processing Jets::PublicController#show
    I, [2019-02-15T20:10:37.105795 #8014]  INFO -- :   Event: {"resource":"/","path":"/","httpMethod":"GET","headers":{"Host":"localhost:8888","User-Agent":"curl/7.53.1","Accept":"*/*","Version":"HTTP/1.1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:10:37.105843 #8014]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:10:37.131045 #8014]  INFO -- : Completed Status Code 200 in 0.025609602s
    127.0.0.1 - - [15/Feb/2019:20:10:37 +0000] "GET / HTTP/1.1" 200 - 0.0602
    
    I, [2019-02-15T20:10:57.173122 #8050]  INFO -- : Started GET "/posts" for 127.0.0.1 at 2019-02-15 20:10:57 +0000
    I, [2019-02-15T20:10:57.173180 #8050]  INFO -- : Processing PostsController#index
    I, [2019-02-15T20:10:57.173243 #8050]  INFO -- :   Event: {"resource":"/posts","path":"/posts","httpMethod":"GET","headers":{"Host":"localhost:8888","User-Agent":"curl/7.53.1","Accept":"*/*","Version":"HTTP/1.1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:10:57.173289 #8050]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:10:57.228170 #8050]  INFO -- : Completed Status Code 200 in 0.055083429s
    127.0.0.1 - - [15/Feb/2019:20:10:57 +0000] "GET /posts HTTP/1.1" 200 - 0.0712
    
    I, [2019-02-15T20:11:11.534508 #8107]  INFO -- : Started GET "/posts" for 11.123.123.123 at 2019-02-15 20:11:11 +0000
    I, [2019-02-15T20:11:11.534564 #8107]  INFO -- : Processing PostsController#index
    I, [2019-02-15T20:11:11.534648 #8107]  INFO -- :   Event: {"resource":"/posts","path":"/posts","httpMethod":"GET","headers":{"Host":"localhost:8888","Connection":"keep-alive","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","Accept-Encoding":"gzip, deflate","Accept-Language":"en-US,en;q=0.9,pt;q=0.8","Version":"HTTP/1.1","upgrade-insecure-requests":"1"},"queryStringParameters":{},"pathParameters":null,"stageVariables":null,"requestContext":{},"body":null,"isBase64Encoded":false}
    I, [2019-02-15T20:11:11.534694 #8107]  INFO -- :   Parameters: {}
    I, [2019-02-15T20:11:11.570395 #8107]  INFO -- : Completed Status Code 200 in 0.035924576s
    11.123.123.123 - - [15/Feb/2019:20:11:11 +0000] "GET /posts HTTP/1.1" 200 - 0.0510

Closing out to not meeting the issues requirements. 👌
